#FROM nvcr.io/nvidia/rapidsai/rapidsai:cuda10.2-runtime-ubuntu18.04
#Changed to Devel image because it includes NVCC, required for apex installation
FROM rapidsai/rapidsai-dev:0.16-cuda10.2-devel-ubuntu18.04-py3.7

ADD ./codes/requirements.txt requirements.txt

#Make RUN commands use the new environment:
SHELL ["conda", "run", "-n", "rapids", "/bin/bash", "-c"]

#Install NVTabular 0.3
RUN mkdir /nvtabular0.3 && cd /nvtabular0.3 && git clone https://github.com/NVIDIA/NVTabular.git && cd NVTabular && pip install -e . && pip install nvtx

#Install latest PyTorch
RUN pip install torch==1.7.0

#Install Apex for --fp16 training with PyTorch < 1.6, otherwise the PyTorch Native AMP is used by the Trainer
#RUN mkdir /apex && cd /apex && git clone https://github.com/NVIDIA/apex && cd apex && pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./

#DLProf (for profiling training loops with NVIDIA Nsights Systems)
RUN pip install nvidia-pyindex && pip install nvidia-pyprof && pip install nvidia-dlprof && pip install nvidia-tensorboard-plugin-dlprof

#Installing framework dependencies
RUN pip install -r requirements.txt;
