#Current session features
item_id-list:
    dtype: categorical
    cardinality: 52740
    is_label: True
    emb_table: item_id-list
    log_with_preds_as_metadata: True

#Control features
timestamp-list:
    dtype: timestamp
    is_control: True #Control features are not uses as input features to the model
    log_with_preds_as_metadata: True           