repos:
      - repo: https://github.com/timothycrosley/isort
        rev: 5.6.4
        hooks:
        - id: isort
          additional_dependencies: [toml]
      - repo: https://github.com/python/black
        rev: 20.8b1
        hooks:
        - id: black
      - repo: https://gitlab.com/pycqa/flake8
        rev: 3.8.4
        hooks:
        - id: flake8
#      - repo: https://github.com/pycqa/pylint
#        rev: pylint-2.7.4
#        hooks:
#        - id: pylint
#      - repo: https://github.com/PyCQA/bandit
#        rev: 1.7.0
#        hooks:
#        - id: bandit
#          args: [--verbose, -ll, -x, tests,examples,bench]
#      - repo: https://github.com/s-weigand/flake8-nb
#        rev: v0.2.7
#        hooks:
#        - id: flake8-nb
#          files: \.ipynb$