repos:
      - repo: https://github.com/timothycrosley/isort
        rev: 5.6.4
        hooks:
        - id: isort
          additional_dependencies: [toml]
      - repo: https://github.com/python/black
        rev: 20.8b1
        hooks:
        - id: black
      - repo: https://gitlab.com/pycqa/flake8
        rev: 3.8.4
        hooks:
        - id: flake8
      - repo: https://github.com/pre-commit/mirrors-mypy
        rev: 'v0.910'
        hooks:
          - id: mypy
            language_version: python3
            args: [--no-strict-optional, --ignore-missing-imports, --show-traceback, --install-types, --non-interactive]
      - repo: https://github.com/codespell-project/codespell
        rev: v2.1.0
        hooks:
        - id: codespell
#      - repo: https://github.com/mgedmin/check-manifest
#        rev: "0.46"
#        hooks:
#          - id: check-manifest
#            args: [--ignore, "*source*"]
#      - repo: https://github.com/pycqa/pylint
#        rev: pylint-2.7.4
#        hooks:
#        - id: pylint
#      - repo: https://github.com/PyCQA/bandit
#        rev: 1.7.0
#        hooks:
#        - id: bandit
#          args: [--verbose, -ll, -x, tests,examples,bench]
#      - repo: https://github.com/s-weigand/flake8-nb
#        rev: v0.2.7
#        hooks:
#        - id: flake8-nb
#          files: \.ipynb$
