repos:
      - repo: https://github.com/timothycrosley/isort
        rev: 5.12.0
        hooks:
        - id: isort
          additional_dependencies: [toml]
      - repo: https://github.com/python/black
        rev: 23.1.0
        hooks:
        - id: black
      - repo: https://github.com/pycqa/flake8
        rev: 6.0.0
        hooks:
        - id: flake8
      - repo: https://github.com/pre-commit/mirrors-mypy
        rev: 'v1.0.1'
        hooks:
          - id: mypy
            language_version: python3
            args: [--non-interactive, --install-types]
      - repo: https://github.com/codespell-project/codespell
        rev: v2.2.2
        hooks:
        - id: codespell
#      - repo: https://github.com/mgedmin/check-manifest
#        rev: "0.46"
#        hooks:
#          - id: check-manifest
#            args: [--ignore, "*source*"]
#      - repo: https://github.com/pycqa/pylint
#        rev: pylint-2.7.4
#        hooks:
#        - id: pylint
#      - repo: https://github.com/PyCQA/bandit
#        rev: 1.7.0
#        hooks:
#        - id: bandit
#          args: [--verbose, -ll, -x, tests,examples,bench]
#      - repo: https://github.com/s-weigand/flake8-nb
#        rev: v0.2.7
#        hooks:
#        - id: flake8-nb
#          files: \.ipynb$
