#Categ features
article_id:
    dtype: categorical
    cardinality: 72933
    is_label: True
    emb_table: article_id
    log_with_preds_as_metadata: True
city:
    dtype: categorical
    cardinality: 1022
    is_label: False
    emb_table: city
    log_with_preds_as_metadata: True
region:
    dtype: categorical
    cardinality: 237
    is_label: False
    emb_table: region
    log_with_preds_as_metadata: True
country:
    dtype: categorical
    cardinality: 70
    is_label: False
    emb_table: country
    log_with_preds_as_metadata: True
device:
    dtype: categorical
    cardinality: 5
    is_label: False
    emb_table: device
    log_with_preds_as_metadata: True
os:
    dtype: categorical
    cardinality: 10
    is_label: False
    emb_table: os
    log_with_preds_as_metadata: True
referrer_class:
    dtype: categorical
    cardinality: 7
    is_label: False
    emb_table: referrer_class
    log_with_preds_as_metadata: True
category0_encoded:
    dtype: categorical
    cardinality: 41
    is_label: False
    emb_table: category0_encoded
    log_with_preds_as_metadata: True
category1_encoded:
    dtype: categorical
    cardinality: 128
    is_label: False
    emb_table: category1_encoded
    log_with_preds_as_metadata: True
author_encoded:
    dtype: categorical
    cardinality: 112
    is_label: False
    emb_table: author_encoded
    log_with_preds_as_metadata: True

#Numerical features
hour_sin:
    dtype: float    
    log_with_preds_as_metadata: True    
hour_cos:
    dtype: float    
    log_with_preds_as_metadata: True    
weekday_sin:
    dtype: float    
    log_with_preds_as_metadata: True    
weekday_cos:
    dtype: float    
    log_with_preds_as_metadata: True
item_age_hours_norm:
    dtype: float    
    log_with_preds_as_metadata: True

#Control features
timestamp:
    dtype: timestamp
    is_control: True #Control features are not uses as input features to the model
    log_with_preds_as_metadata: True     