FROM nvcr.io/nvidia/merlin/merlin-pytorch-training:0.5.3

ADD ./transformers4rec/requirements.txt requirements.txt

#Make RUN commands use the new environment:
SHELL ["conda", "run", "-n", "merlin", "/bin/bash", "-c"]

#echo "Installing dependencies"
RUN pip install -r requirements.txt

################ Setup GitHub repo ################

ARG SSH_KEY

# Make ssh dir
RUN echo "Setting up GitHub repo"
RUN mkdir /root/.ssh/

# "Copying" GitHub Deployment private key for the NVIDIA-Merlin/Transformers4Recrepo
# For that, you need to provide --build-arg SSH_KEY="$(cat ~/.ssh/transf4rec_ngc_repo_key)" when building, pointing to the path of the private SSH key 
RUN echo "$SSH_KEY" > /root/.ssh/transf4rec_ngc_repo_key

# Configures the SSH key
RUN apt-get update && apt-get install -y openssh-client
RUN chmod 600 /root/.ssh/transf4rec_ngc_repo_key && \
  echo "IdentityFile /root/.ssh/transf4rec_ngc_repo_key" >> /etc/ssh/ssh_config && \
  echo -e "StrictHostKeyChecking no" >> /etc/ssh/ssh_config

WORKDIR /workspace

# Clone repo and checkout to the "main" branch
RUN git clone --branch 'main' --single-branch --depth 1 git@github.com:NVIDIA-Merlin/Transformers4Rec.git

################################################################
