#Current session features
sess_pid_seq:
    dtype: categorical
    cardinality: 390000
    is_label: True
    emb_table: product_id
    log_with_preds_as_metadata: True
sess_session_reversed_order_seq:
    dtype: categorical
    cardinality: 30
    emb_table: session_order
    log_with_preds_as_metadata: True
sess_dtime_secs_log_norm_seq:
    dtype: float 
    log_with_preds_as_metadata: True  

# Past session interactions
bef_sess_pid_seq:
    dtype: categorical
    cardinality: 390000
    emb_table: product_id
    log_with_preds_as_metadata: True
bef_sess_session_reversed_order_seq:
    dtype: categorical
    cardinality: 30
    emb_table: session_order
    log_with_preds_as_metadata: True
bef_sess_dtime_secs_log_norm_seq:
    dtype: float 
    log_with_preds_as_metadata: True   

#Control features
sess_etime_seq:
    dtype: timestamp
    is_control: True #Control features are not uses as input features to the model
    log_with_preds_as_metadata: True        